version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:15-bullseye
    container_name: database
    environment:
      POSTGRES_DB: 'hospital_db'
      POSTGRES_USER: 'bagas'
      POSTGRES_PASSWORD: '12345'
      PG_DATA: '/var/lib/postgresql/data'
    ports:
      - "5438:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
 
volumes:
  db-data:
    external: false